### ISSUE TITLE
Configuring project

### ISSUE THREAD

**Issue by xbeheydt** [xbeheydt/GameDev-grafel#1]
# Tasks

- [ ] Prepare CMake
  - [ ] Base of project architecture
  - [ ] First settings
  - [ ] Create a module download vcpkg
  - [ ] Define first dependancies
  - [ ] Holds clang compilator or not ?
  - [ ] Prepare to Python
- [ ] EditorConfig
- [ ] clang-format
- [ ] clang-tidy
- [ ] GitHub Actions
  - [ ] Run tests and coverages (only if work in remote)
  - [ ] Generate documentation and add to github pages
  - [ ] Generate Releases

# Sources

1. https://gitlab.com/CLIUtils/modern-cmake
2. https://cliutils.gitlab.io/modern-cmake/
3. https://clang.llvm.org/docs/ClangFormatStyleOptions.html
4. https://github.com/microsoft/vcpkg?tab=readme-ov-file#quick-start-windows
